#! /bin/sh
#
# $Id: masq-down,v 1.1 2002/07/12 12:44:06 kds Exp $
#
# Stop masquerading for a PPP connection
#

if [ "$PPP_IPPARAM" == "MASQUERADE" ] ; then
	iptables -t nat -D POSTROUTING -j MASQUERADE -s $PPP_REMOTE
fi

exit 0

