


set( CMAKE_C_FLAGS      "${CMAKE_C_FLAGS} -g -Wall -O2 -DDEBUG -O -DSOCKLEN_T=socklen_t  -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64  " )  
set( CMAKE_CXX_FLAGS    "${CMAKE_CXX_FLAGS} -g -Wall -O2 -DDEBUG -O -DSOCKLEN_T=socklen_t  -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64  " ) 






